name: release version
on:
  push:
    branches:
      - master
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: get old changelog length
        run: OLD_CHANGELOG_LENGTH = wc -l < ./CHANGELOG.md
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx standard-version
      - name: get changelog diff
        run: |
         NEW_CHANGELOG_LENGTH = wc -l < ./CHANGELOG.md 
         NEW_LINES_COUNT =$(expr $NEW_CHANGELOG_LENGTH - $OLD_CHANGELOG_LENGTH)
         cat CHANGELOG.md | head -n $NEW_LINES_COUNT > notification.md
         cat ./notification.md 
